(require "comm")

(define-lw-system lw-fcgi ()
  (:system "lw-date")
  (:system "lw-json")
  (:system "lw-mime")
  (:system "lw-utils")
  (:file "fcgi" :depends-on "package")
  (:file "fetch" :depends-on "route")
  (:file "package")
  (:file "route" :depends-on "fcgi"))
